# Site settings
title: Chris Zumbika's Portfolio
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "cotzanium.github.io" # the base hostname & protocol for your site

# User setting
owner: Chris Zumbika
email: name@example.com
facebook_name: example
500px_name: cotzanium
github_name: cotzanium
linkedin_name: chriszumbika
address:
  - line: Braamfontein
  - line: "Johannesburg, Gauteng 2001"
  # Feel free to add more lines here 
copyright: cotzanium

# API settings

# Build settings
markdown: kramdown